version: 2

sources:
  
  - name: smart_meters_files
    description: "smart meters are located in U.K."
    database: pmv_files
    schema: pmv_files
    tables:
      - name: PMV_COMMSHUB
      - name: chsu
      - name: override
      - name: exception

